PG 16 initial version
apache/age pull request #1237
Opened 2023-09-20 11:32 UTC by muhammadshoaib

Fixed empty string handling

Previously, the PG 16 outToken emitted `NULL` for an empty string, but now it emits an empty string `""`. Consequently, our cypher read function required modification to properly decode the empty string as a plain token, thereby addressing the comparison issue. 

Compared the branches and added the necessary changes so that the query's `rteperminfos` variable doesn't stay `NULL`.

Fix missing include varatt.h (causing undefined symbol `VARDATA_ANY)` & Fixing some test cases of the failings

Added missing include `varatt.h` to fix the undefined symbol while loading age into postgresql because usage of `VARDATA_ANY` needs to import `varatt.h` in PG16

Modified initialisation of `ResultRelInfo` and removed unnecessary `RTEs`

Compared the branches and added the necessary changes so that the query's `rteperminfos` variable doesn't stay `NULL`.

Modified initialisation of `ResultRelInfo` and removed unnecessary `RTEs`

One of the problems that we were facing was related to the `ResultRelInfo` pointing at the wrong `RTE` via its `ri_RangeTableIndex`. The `create_entity_result_rel_info()` function does not have the capability of setting the `ri_RootResultRelInfo` to the correct `ResultRelInfo` node because it does not have access to the `ModifyTableState` node. The solution for this was to set the third argument in `InitResultRelInfo()` to be zero instead of `list_length(estate->es_range_table)`.

In the `update_entity_tuple()` function, when we call `table_tuple_update()` and assign the returned value to the result variable, the buffer variable receives the value of 0.
Made a workaround so that the original value isn't lost.

This is a work in progress for the new field that was added to the struct Var called `varnullingrels`. According to the documentation, this field is responsible for marking the Vars as nullable, if they are coming from a `JOIN`, either `LEFT JOIN`, `RIGHT JOIN`, or `FULL OUTER JOIN`. The changes were made following an "optional match" clause which is being treated as a `LEFT JOIN` from our extension.

A function `markRelsAsNulledBy` is added because its internal in Postgres and doesn't belong in a header file, therefore it can't be exported. This function is added before the creation of the Vars from the `make_vertex_expr` and `make_edge_expr`, to correctly mark the specific `PNSI` as `nullable`, so later in the planner stage, the Vars will be correctly nulled.

Fix incorrect typecasting in `agtype_to_graphid` function. 

Fix incorrect returns to the fuction `_label_name`, `_ag_build_vertex` and `_ag_build_edge`.

2023-10-17 00:28 UTC, jrgemignani requested changes

2023-10-17 00:28 UTC, jrgemignani commented on .github/workflows/go-driver.yml
> +    branches: [ "master", "pg16" ]
All `pg16 ` entries need to be uppercase `PG16`. Except where that `pg15` is lowercase.

2023-10-17 00:28 UTC, jrgemignani commented on .github/workflows/installcheck.yaml
> +    branches: [ 'master', 'pg16' ]
All `pg16 ` entries need to be uppercase `PG16`. Except where that `pg15` is lowercase.

2023-10-17 00:28 UTC, jrgemignani commented on .github/workflows/jdbc-driver.yaml
> +    branches: [ "master", "pg16" ]
All `pg16 ` entries need to be uppercase `PG16`. Except where that `pg15` is lowercase.

2023-10-17 00:28 UTC, jrgemignani commented on .github/workflows/nodejs-driver.yaml
> +    branches: [ "master", "pg16" ]
All `pg16 ` entries need to be uppercase `PG16`. Except where that `pg15` is lowercase.

2023-10-17 00:28 UTC, jrgemignani commented on .github/workflows/python-driver.yaml
> +    branches: [ "master", "pg16" ]
All `pg16 ` entries need to be uppercase `PG16`. Except where that `pg15` is lowercase.

2023-10-17 00:29 UTC, jrgemignani commented
@muhammadshoaib only a partial review, more to come.

2023-10-17 16:56 UTC, jrgemignani requested changes
Please go through the **entire** patch and make sure that -

1. No braces are being removed for just one line `if/else`.
2. Braces are on their **own** line, by themselves.

2023-10-17 16:56 UTC, jrgemignani commented on src/backend/utils/adt/agtype.c
> +        i = 0;
If this `i` is only used within this `if` block, then let's only have it defined here. If this `i` is used outside of this `if` block for other things, then let's change the interior `i` to some other variable name. Let's try to keep the scope of the variable as close to where it is used and let's not duplicate variables unless absolutely necessary.

2023-10-17 16:56 UTC, jrgemignani commented on src/backend/parser/cypher_gram.y
> -            {
Why remove the surrounding braces?

2023-10-17 16:56 UTC, jrgemignani commented on src/backend/parser/cypher_gram.y
> -            }
Why remove the surrounding braces?

2023-10-17 16:56 UTC, jrgemignani commented on src/backend/parser/cypher_expr.c
> -        {
Why are the braces being removed?

2023-10-17 16:56 UTC, jrgemignani commented on src/backend/parser/cypher_expr.c
> +        if (ac->isnull) {
Braces do *not* go at the end of the line of code, they go on the following line.,

2023-10-31 13:39 UTC, jirutka commented
We are planning to release Alpine v3.19 in November and I’d really love to include AGE in this release. The problem is that is must be built against the latest PostgreSQL, i.e. version 16.

2023-11-06 19:16 UTC, jrgemignani commented
> We are planning to release Alpine v3.19 in November and I’d really love to include AGE in this release. The problem is that is must be built against the latest PostgreSQL, i.e. version 16.

Our PG16 branch is currently in the final stages of review. It should be ready in a ~2 weeks. @muhammadshoaib ?

2023-11-06 22:37 UTC, jrgemignani commented
@muhammadshoaib Please review the **build** log -

```
src/backend/executor/cypher_merge.c: In function ‘exec_cypher_merge’:
src/backend/executor/cypher_merge.c:475:26: warning: declaration of ‘econtext’ shadows a previous local [-Wshadow=compatible-local]
  475 |             ExprContext *econtext = node->ss.ps.ps_ExprContext;
      |                          ^~~~~~~~
src/backend/executor/cypher_merge.c:320:[18](https://github.com/apache/age/actions/runs/6769752846/job/18396782787?pr=1237#step:6:19): note: shadowed declaration is here
  3[20](https://github.com/apache/age/actions/runs/6769752846/job/18396782787?pr=1237#step:6:21) |     ExprContext *econtext = css->css.ss.ps.ps_ExprContext;
      |                  ^~~~~~~~
```

2023-11-06 23:06 UTC, jrgemignani requested changes

2023-11-06 23:06 UTC, jrgemignani commented on src/backend/utils/adt/agtype.c
> +        /*
Don't leave in commented out code please :)

2023-11-06 23:06 UTC, jrgemignani commented on src/backend/utils/adt/agtype.c
> +        i = 0;
Still needs to be fixed.

2023-12-05 19:52 UTC, jrgemignani requested changes

2023-12-05 19:52 UTC, jrgemignani commented on src/backend/parser/cypher_clause.c
> +        //RangeVar *rv;
Commented out?

2023-12-05 19:52 UTC, jrgemignani commented on src/backend/parser/cypher_clause.c
> +        //RangeVar *rv;
Commented out?

2023-12-05 19:52 UTC, jrgemignani commented on src/backend/parser/cypher_clause.c
> +        //RangeVar *rv;
Commented out?

2023-12-12 19:53 UTC, jrgemignani approved these changes

2023-12-12 19:57 UTC, merged

2024-03-11 16:36 UTC, jrgemignani commented
@jirutka Could you respond to #1652 ?

2024-03-14 10:09 UTC, pras-baghel commented
Please share steps and needed binaries for installing age extension on alpine-3.19.1 image.