Modify COUNT() to output agtype
apache/age pull request #1311
Opened 2023-10-26 21:36 UTC by dehowef

Modified the make_function_expr logic to wrap the PG COUNT() function with a cast to agtype. This enables COUNT() to be used as a subquery in CASE.

Also added logic for casting for future PG function additions.

This modification passes all regression tests. Also added regression tests for COUNT in CASE statements.

2023-10-27 19:37 UTC, jrgemignani requested changes
One minor issue with else missing {}

Also, would it be possible to combine `make_function_expr`, `make_star_function_expr`, and `make_distinct_function_expr `into one? with flags passed? There appears to be a lot of duplicate code between them.

2023-10-27 19:37 UTC, jrgemignani commented on src/backend/parser/cypher_gram.y
> +    else
Missing {}

2023-10-27 23:41 UTC, dehowef commented
> One minor issue with else missing {}
> 
> Also, would it be possible to combine `make_function_expr`, `make_star_function_expr`, and `make_distinct_function_expr `into one? with flags passed? There appears to be a lot of duplicate code between them.

Added the parentheses

2023-10-28 00:36 UTC, jrgemignani approved these changes

2023-10-30 21:39 UTC, merged

2023-10-30 21:41 UTC, rafsun42 approved these changes