Implement EXISTS subquery for CASE
apache/age pull request #1345
Opened 2023-11-02 00:15 UTC by dehowef

Modified logic of EXISTS to wrap itself in a agtype cast. This allows EXISTS to work with in CASE statements, among other implementations that may require an agtype.

Also renamed the wrapper function to be more generic to denote its usage in other implementations if need be.

Added regression tests for EXISTS.

2023-11-03 14:33 UTC, jrgemignani requested changes
minor cosmetic

2023-11-03 14:33 UTC, jrgemignani commented on src/backend/parser/cypher_gram.y
> +
extra line?

2023-11-03 21:47 UTC, dehowef commented on src/backend/parser/cypher_gram.y
> +
addressed

2023-11-07 00:33 UTC, jrgemignani approved these changes

2023-11-07 00:33 UTC, merged